#GRAPH 1 — Survival Count (Bar Chart)
df['Survived'].value_counts().plot(kind='bar')
plt.title("Survival Count")
plt.xlabel("Survived (0 = No, 1 = Yes)")
plt.ylabel("Count")
plt.show()

#GRAPH 2 — Survival by Gender (Grouped Bar)
df.groupby(['Sex','Survived']).size().unstack().plot(kind='bar')
plt.title("Survival by Gender")
plt.xlabel("Gender")
plt.ylabel("Count")
plt.legend(["Not Survived","Survived"])
plt.show()

#GRAPH 3 — Passenger Class Distribution (Pie Chart)
df['Pclass'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Passenger Class Distribution")
plt.ylabel("")
plt.show()

#GRAPH 4 — Age Distribution (Histogram)
df['Age'].hist(bins=20)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

#GRAPH 5 — Fare vs Class (Box Plot)
df.boxplot(column='Fare', by='Pclass')
plt.title("Fare vs Passenger Class")
plt.xlabel("Class")
plt.ylabel("Fare")
plt.show()